/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  slfx7
 * Created: Dec 2, 2018
 */

drop table LinkedUDB.appointments;

CREATE TABLE LinkedUDB.appointments (
  appointmentId             INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  startTime                 TIME,
  endTime                   TIME,
  aptDate                   DATE,
  universityId              INT NOT NULL,
  studentId                 INT
--   FOREIGN KEY (universityId)
--     REFERENCES LinkedUDB.UNIVERSITIES (universityId),
--  FOREIGN KEY (studentId)
--    REFERENCES LinkedUDB.STUDENTS (studentId)
);

INSERT INTO LINKEDUDB.APPOINTMENTS (STARTTIME, ENDTIME, APTDATE, UNIVERSITYID, STUDENTID) 
	VALUES ('15:18:17', '16:00:00', '2018-12-05', 1, NULL);
INSERT INTO LINKEDUDB.APPOINTMENTS (STARTTIME, ENDTIME, APTDATE, UNIVERSITYID, STUDENTID) 
	VALUES ('18:00:00', '19:00:00', '2018-12-14', 4, NULL);
INSERT INTO LINKEDUDB.APPOINTMENTS (STARTTIME, ENDTIME, APTDATE, UNIVERSITYID, STUDENTID) 
	VALUES ('17:00:00', '18:00:00', '2018-12-14', 4, NULL);
INSERT INTO LINKEDUDB.APPOINTMENTS (STARTTIME, ENDTIME, APTDATE, UNIVERSITYID, STUDENTID) 
	VALUES ('16:00:00', '17:00:00', '2018-12-14', 4, NULL);
INSERT INTO LINKEDUDB.APPOINTMENTS (STARTTIME, ENDTIME, APTDATE, UNIVERSITYID, STUDENTID) 
	VALUES ('15:00:00', '16:00:00', '2018-12-14', 4, 6);
INSERT INTO LINKEDUDB.APPOINTMENTS (STARTTIME, ENDTIME, APTDATE, UNIVERSITYID, STUDENTID) 
	VALUES ('14:00:00', '15:00:00', '2018-12-14', 4, NULL);


